### ISSUE TITLE
Example usecases?

### ISSUE THREAD

**Issue by joshwcomeau** [Slgoetz/lemniscate#1]
Hi Simon,

Interesting project; reminds me of the curved stairwell to Bowser in Super Mario 64.

I'm curious what inspired this project, and what the typical usecase(s) are? 

Thanks :)

**Comment by Slgoetz** [comment]
Hi @joshwcomeau.  The idea was inspired by a client project - [Ghost Robot](http://ghostrobot.com) - then nudged by an admirer who wanted to know how we created this effect.  This plugin was completed fairly quickly, but we do hope to refine it for people who want users to get lost in their work.

**Comment by joshwcomeau** [comment]
Thanks for the info :) makes sense!
