### ISSUE TITLE
vanilla js or npm 

### ISSUE THREAD

**Issue by adamjw3** [Slgoetz/lemniscate#3]
Hi Simon,

This is really cool, i've been looking for something that can do this to use in a react project that has https://github.com/locomotivemtl/locomotive-scroll for smooth scrolling and detecting items in view

Do you have this as npm package without jquery dependency?

One line i wanted to ask you about.

$(o.container).parent().prepend( loop_clone ).append( loop_clone ); (line 20)

you have prepend and append but i only see one clone of the content when i inspect

Thanks :)

**Comment by Slgoetz** [comment]
I actually need to rebuild this entire repo. The entire thing is outdated.

**Comment by adamjw3** [comment]
I did something on https://pickuppeople.co/ 

Better on desktop.

**Comment by Slgoetz** [comment]
That's awesome. Looks great.
